spring:
  cloud:
    stream:
      function:
        definition: getOrderEventAndProcess
      bindings:
        getOrderEventAndProcess-in-0:
          destination: order-event
        getOrderEventAndProcess-out-0:
          destination: payment-event


